name: Run Gradle on push
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build